### ISSUE TITLE
input sub-object in a workflow results in panic

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-engine#30]
## Describe the bug

Adding a sub-object to the `input` section of a workflow and incorporating it into the root object as a `ref` causes a panic when running the workflow.

## To reproduce

This is using the [workflows branch](https://github.com/arcalot/arcaflow-engine/tree/workflows) of the engine. (now [main](https://github.com/arcalot/arcaflow-engine/tree/main/))

workflow.yaml:
```yaml
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        subobject:
          type:
            type_id: ref
    subobject:
      id: subobject
      properties:
        foo:
          type:
            type_id: string
steps:
  narf:
    plugin: narf
    input: {}
output: {}
```

input.yaml
```yaml
subobject:
  foo: bar
```

Running the workflow:
```
$ go run cmd/arcaflow/main.go -input input.yaml
panic: Unserialize called before ApplyScope. Did you add your RefType to a scope?

goroutine 1 [running]:
go.flow.arcalot.io/pluginsdk/schema.(*RefSchema).Unserialize(0x15a4280?, {0x15a0f20?, 0xc00017f5c0?})
	/home/dblack/go/pkg/mod/go.flow.arcalot.io/pluginsdk@v0.0.0-20221019080109-e8dfaa8c4c43/schema/ref.go:97 +0x7c
go.flow.arcalot.io/pluginsdk/schema.(*PropertySchema).Unserialize(...)
	/home/dblack/go/pkg/mod/go.flow.arcalot.io/pluginsdk@v0.0.0-20221019080109-e8dfaa8c4c43/schema/property.go:115
go.flow.arcalot.io/pluginsdk/schema.(*ObjectSchema).convertData(0xc0005ecf00, {0x15a0f20?, 0xc00017f590?, 0x17b0b09?})
	/home/dblack/go/pkg/mod/go.flow.arcalot.io/pluginsdk@v0.0.0-20221019080109-e8dfaa8c4c43/schema/object.go:385 +0x349
go.flow.arcalot.io/pluginsdk/schema.(*ObjectSchema).Unserialize(0xc0005ecf00, {0x15a0f20?, 0xc00017f590?})
	/home/dblack/go/pkg/mod/go.flow.arcalot.io/pluginsdk@v0.0.0-20221019080109-e8dfaa8c4c43/schema/object.go:84 +0x14a
go.flow.arcalot.io/pluginsdk/schema.(*ScopeSchema).Unserialize(...)
	/home/dblack/go/pkg/mod/go.flow.arcalot.io/pluginsdk@v0.0.0-20221019080109-e8dfaa8c4c43/schema/scope.go:67
go.flow.arcalot.io/engine.workflowEngine.RunWorkflow({{0x1a36640, 0xc00017e960}, {0x1a2a710, 0xc00041a448}, 0xc0001da3c0}, {0x1a35998?, 0xc0005e58c0}, {0xc00013de00, 0x16, 0x200}, ...)
	/home/dblack/git/arcaflow-engine/engine.go:62 +0x187
main.main()
	/home/dblack/git/arcaflow-engine/cmd/arcaflow/main.go:124 +0xa37
exit status 2
```
