### ISSUE TITLE
Allow workflow input parameter defaults to be implied by the underlying plugin defaults

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-engine#68]
## Please describe what you would like to see in this project

Currently if an input parameter is not required and is left unset, but then that parameter is referenced for the input to a plugin, the engine will error because the value is unset.

```
2023-04-04T10:00:29+02:00	error		Workflow execution failed (failed to expand step pcp input parameters (map key pcp_pmlogger_interval not found))
```

Instead, where possible, the default value should be inferred from the plugin and allow the workflow input to be unset.

## Please describe your use case

A workflow should be flexible enough to accept inputs and defaults in the same ways that the underlying plugins do. Implied parameters from plugin defaults make workflows more user-friendly and portable across use cases.

## Additional context

Example workflow snippet demonstrating the problem, where the `pmlogger_interval` has no default (and is not provided by the `input.yaml`).

```
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        pcp_pmlogger_interval:
          display:
            description: The logger collection interval for PCP pmlogger
            name: PCP pmlogger collection interval
          type:
            type_id: integer
          required: false

steps:
  pcp:
    plugin: quay.io/arcalot/arcaflow-plugin-pcp:0.2.0
    step: start-pcp
    input:
      pmlogger_interval: !expr $.input.pcp_pmlogger_interval
      run_duration: !expr $.input.time

output:
  pcp: !expr $.steps.pcp.outputs.success
```

You can see in the pcp plugin that the `pmlogger_interval` parameter is optional with a `None` default.

```
    pmlogger_interval: typing.Annotated[
        typing.Optional[int],
        schema.name("pmlogger logging interval"),
        schema.description(
            "The logging interval in seconds used by "
            "pmlogger for data collection"
        ),
    ] = None
```
